name: Deploy Supabase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Supabase CLI
        run: |
          npm install -g supabase
          supabase login --token ${{ secrets.SUPABASE_TOKEN }}

      - name: Deploy to Supabase
        run: supabase db push
